name: Grumpy spam filter
on:
  pull_request_target:
    types: [opened, reopened]
jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - name: Grumpy
        uses: ./
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
